---
- name: Install/activate rust via mise (global)
  command: "{{ ansible_facts['env']['HOME'] }}/.local/bin/mise use -g rust"
  register: mise_rust
  changed_when: "'installed' in (mise_rust.stdout | lower) or 'installed' in (mise_rust.stderr | lower)"
