---
git_user_name: "Erik Thorsell"
git_user_email: "erik@thorsell.io"
git_home: "{{ ansible_env.HOME }}"
work_root: "{{ git_home }}/work"
common_path: "{{ role_path }}/files/gitconfig_common"
customer_src_root: "{{ role_path }}/files/customers"

