---
- name: Ensure temp download directory exists
  file:
    path: "{{ github_release_dest }}"
    state: directory
    mode: '0755'

- name: Fetch latest release metadata from GitHub
  get_url:
    url: "https://api.github.com/repos/{{ github_release_repo }}/releases/latest"
    dest: "/tmp/github_release_manifest"
    headers:
      Accept: application/vnd.github.v3+json
  register: github_release

- name: Pattern match to get correct Download URL
  set_fact:
    github_release_asset_url: >-
      {{ github_release.json.assets
         | selectattr('name','match', github_release_asset_pattern)
         | map(attribute='browser_download_url')
         | first
      }}

- name: Download GitHub release asset
  get_url:
    url: "{{ github_release_asset_url }}"
    dest: "{{ github_release_dest }}/{{ github_release_asset_url | basename }}"
    mode: '0644'

