---
- name: Download latest ASDF via GitHub helper
  include_role:
    name: github_release
  vars:
    github_release_repo: "asdf-vm/asdf"
    github_release_asset_pattern: "asdf-[^/]+-linux-amd64\\.tar\\.gz$"
    github_release_dest: "/tmp/github_release/asdf"
    github_release_overwrite: yes

- name: Find ASDF tarball
  find:
    paths: "/tmp/github_release/asdf"
    patterns: "asdf-*-linux-amd64.tar.gz"
    file_type: file
  register: asdf_tar

- name: Unpack ASDF tarball
  become: yes
  unarchive:
    src:  "{{ asdf_tar.files[0].path }}"
    dest: "/usr/local/bin"
    remote_src: yes
  when:
    - asdf_tar.matched == 1

- name: Get installed ASDF version
  command: "/usr/local/bin/asdf --version"
  register: asdf_version
  failed_when: asdf_version.rc != 0

