# Change prefix key to Ctl + A
unbind C-b
set -g prefix C-a
bind C-a send prefix

# Navigate panes with jklö
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# 
