#!/bin/bash

INTERFACE="${1:-}"
LABEL="${2:-}"
#LABEL=""

state="$(cat /sys/class/net/$INTERFACE/operstate)"

wifi="$(cat /sys/class/net/wlp3s0/operstate)"
ethernet="$(cat /sys/class/net/enp0s25/operstate)"

if [ "$wifi" != "up" and "$ethernet" != "up" ]; then
	echo "$LABEL down"
	echo "$LABEL down"
	echo "#FF0000"
	exit 0
fi

ipaddr=$(wget http://ipinfo.io/ip -qO -)

echo "$LABEL$ipaddr"
