---
- name: Ensure latest version of Vim is installed
  become: yes
  apt:
    name: vim-gtk3  # vim-gtk3 has +clipboard
    state: latest

- name: Ensure ~/.vim and its runtime dirs exist
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ""
    - autoload
    - plugged
    - swap
    - undo
    - config

- name: Symlink vimrc
  file:
    src:  "{{ role_path }}/files/vimrc"
    dest: "{{ ansible_env.HOME }}/.vimrc"
    state: link
    force: yes

- name: Symlink vim configurations
  file:
    src:  "{{ role_path }}/files/config"
    dest: "{{ ansible_env.HOME }}/.vim/config"
    state: link
    force: yes

