- name: Configure Ubuntu workstation
  hosts: ubuntu
  gather_facts: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_become_exe: sudo
  pre_tasks:
    - name: Detect sudo
      stat:
        path: /usr/bin/sudo
      register: sudo_bin

    - name: Detect dzdo
      stat:
        path: /usr/bin/dzdo
      register: dzdo_bin

    - name: If dzdo is present and sudo is not, use dzdo
      set_fact:
        ansible_become_exe: dzdo
      when: not sudo_bin.stat.exists and dzdo_bin.stat.exists

  roles:
    # Basic tools and config
    - role: bash
    - role: bat
    - role: delta
    - role: eza
    - role: fd
    - role: git
    - role: ghostty
      tags: [ghostty]
    - role: neovim
    # Managed via mise | If you don't have mise, these will fail.
    - role: gitui
    - role: kubectl
    - role: kustomize
    - role: nodejs
    - role: opentofu
    - role: ripgrep
    - role: talosctl
    - role: tree-sitter
    - role: yq
    # Applications from apt
    - role: apt_pkgs
      tags: [apt]
    - role: upgrade
      tags: [apt]

